### ISSUE TITLE
harriet pluginの挙動が本家のproveと違う

### ISSUE THREAD

**Issue by shogo82148** [shogo82148/go-prove#21]
> macopy [11:55 AM] 
> @shogo82148 go-proveのharriet pluginの挙動が本家のproveと違うからどないやねんみたいな話をしております
> 
> 
> [11:55] 
> 具体的に言うと本家は-j4でも1回しか実行されないけれどgo-proveはワーカーごとに走る
>

**Comment by shogo82148** [comment]
この件については、実は実装したあとに気がついていたのですが放置してました・・・ゴメンナサイ。

まこぴー氏の言うとおりニーズはあると思うので、以下の方針はどうでしょう？

- go-proveのharriet pluginは本家proveと挙動を合わせる
- ワーカーごとに走るよう改造したharrietをCPANに上げる(harriet::parallel...とか？)
  - 現状の go-prove harriet plugin はこっちの名前にリネーム

**Comment by mackee** [comment]
それで良いと思います Harriet::Parallel 的な挙動はワタクシ的には今すぐ無くても良いのでどうせ互換性崩れるなら先に本家と合わせるでよいかと

**Comment by shogo82148** [comment]
では、とりあえずこっちはシュッと対応します。

> go-proveのharriet pluginは本家proveと挙動を合わせる

**Comment by shogo82148** [comment]
#22 で対応済み
